### ISSUE TITLE
Missing class BuyerXmlReader

### ISSUE THREAD

**Issue by massgiu** [gioce90/TransferSimulation-JADE-Multi-agent-System#1]
Inside class BuyerAgent.java there's a reference to BuyerXmlReader class, but it's absent inside the package XmlParser. Could you please fix it?

**Comment by gioce90** [comment]
I don't work anymore on this project, but I noticed that this is a really old version (year 2014). My mistake.
I have a newer and working version (year 2015). I can put the update tomorrow on GitHub. See you soon.

**Comment by massgiu** [comment]
Thank you very much.
Best regards.

Il 09 ago 2017 2:20 PM, "Gioacchino Piazzolla" <notifications@github.com>
ha scritto:

**Comment by gioce90** [comment]
Hi,
Please try the new branch UpdatedBranch. I haven't tested, but it should works

**Comment by massgiu** [comment]
Ok, I will test it as soon as possibile and I will give you feedback.
Thanks.

Il 10 ago 2017 10:31 AM, "Gioacchino Piazzolla" <notifications@github.com>
ha scritto:

**Comment by gioce90** [comment]
Hi. Have you tested the branch? It works?

**Comment by massgiu** [comment]
Hi, everything was fine; thank you.

Il 04 nov 2017 21:07, "Gioacchino Piazzolla" <notifications@github.com> ha
scritto:

Hi. Have you tested the branch? It works?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gioce90/TransferSimulation-JADE-Multi-agent-System/issues/1#issuecomment-341926123>,
or mute the thread
